doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            bnom: DoctrineExtensions\Types\BnomType
            bnom[]: DoctrineExtensions\Types\BnomArrayType
            leam: DoctrineExtensions\Types\LeamType
            leam[]: DoctrineExtensions\Types\LeamArrayType
            bcut: DoctrineExtensions\Types\BnomArrayType
            docdatetime: DoctrineExtensions\Types\DoctrineDateTimeType
            tstzrange: DoctrineExtensions\Types\TsTzRangeType
            int2range: DoctrineExtensions\Types\Int2RangeType
        mapping_types:
            _bnom: bnom
            bnom[]: array
            _leam: leam
            leam[]: array
            tstzrange: tstzrange
            _bpchar: string
            int2range: int2range
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            # ManualBundle:
            #     is_bundle: true
            #     type: attribute
            #     dir: Entity
            #     prefix: 'ManualBundle\Entity'
            #     alias: ManualBundle
        dql:
            numeric_functions:
                standard_length: App\Query\StandardLength
                volume_timber: App\Query\VolumeTimber
                unnest: DoctrineExtensions\Query\Postgresql\Unnest
                volume_boards: DoctrineExtensions\Query\Postgresql\VolumeBoard
                get_json_filed_by_key: DoctrineExtensions\Query\Postgresql\GetJsonFieldByKey
                get_int_into_by_key: DoctrineExtensions\Query\Postgresql\GetIntIntoJsonByKey
                cast: DoctrineExtensions\Query\Postgresql\Cast
                array_length: DoctrineExtensions\Query\Postgresql\ArrayLength
                now: DoctrineExtensions\Query\Postgresql\NowTime
                age: DoctrineExtensions\Query\Postgresql\Age
                date_part: DoctrineExtensions\Query\Postgresql\DatePart
                concat_ws: DoctrineExtensions\Query\Mysql\ConcatWs
                # concat: DoctrineExtensions\Query\Mysql\ConcatWs
